baseurl = "https://www.cristianmarquez.me"
title = "Cristian M치rquez Russo"

theme = ["hugo-notice","hugo-cloak-email","hugo-coder"]
googleAnalytics = "UA-66128333-1"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "cristianmarquez"

enableEmoji = true


[params]
    author = "Cristian M치rquez Russo"
    description = "I post about technology and trips"
    keywords = "Cloud, Docker, Kubernetes, Trips, Travel, Holidays"
    info = "Technology and Trips"
    avatarurl = "/images/me.jpg"
    footercontent = "游낺"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/cristian04/hugo-website/commits/master"

    rtl = false

    # Use inverted colors
    inverted = true

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/cristian04"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/cmarquezrusso"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/cristianmarquezrusso"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 3
        url = "/posts/"

        #[[languages.en.menu.main]]
        #name = "Projects"
        #weight = 3
        #url = "/projects/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "/contact/"


    [languages.es]
        languagename = "Espa침ol"
        title = "Cristian M치rquez Russo"

        [languages.es.params]
            author = "Cristian M치rquez Russo"
            info = "Tecnolog칤a y Viajes"
            description = "Sitio con informacion sobre tecnologia y viajes."
            keywords = "devops, site reliabilty engineer, trips"
            footercontent = "游낺"

        [languages.es.menu]

            [[languages.es.menu.main]]
            name = "Acerca de mi"
            weight = 1
            url = "/es/about/"

            [[languages.es.menu.main]]
            name = "Blog"
            weight = 3
            url = "/es/posts/"

            #[[languages.es.menu.main]]
            #name = "Proyectos"
            #weight = 3
            #url = "/es/projects/"

            [[languages.es.menu.main]]
            name = "Contacto"
            weight = 5
            url = "/es/contact/"
